#!/usr/bin/env bash
echo "put object"

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

bucket_name=$1

output_dir="/tmp/s3-objects"

# Check if the directory exists
if [ -d "$output_dir" ]; then
  # If it exists, remove it recursively
  rm -r "$output_dir"
  echo "Removed directory: $output_dir"
else
  echo "Directory does not exist: $output_dir"
fi

mkdir -p $output_dir

filename=$output_dir/tempfile.txt
    
# Create an empty file with the generated name
touch "$filename"

object_key=$(basename $filename) 

aws s3api put-object \
--key $object_key \
--body $filename \
--bucket $bucket_name

