#!/usr/bin/env bash
STACK_NAME="sam-python-lambda-function-stack"

echo "SAM deploy..."

sam deploy \
--template-file "./.aws-sam/build/template.yaml" \
--stack-name $STACK_NAME \
--capabilities CAPABILITY_IAM