#!/usr/bin/env bash
echo "sync objects into bucket"

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

bucket_name=$1

output_dir="/tmp/s3-objects"

rm -r $output_dir

mkdir -p $output_dir

# Loop to create 5 files
for i in {1..5}; do
    # Generate a random file name using UUID
    filename=$output_dir/file_$i.txt
    
    # Create an empty file with the generated name
    touch "$filename"
    
    # Optionally, you can add some random content to the file
    echo "Random content for $filename" > "$filename"
    
    echo "Created file: $filename"
done

tree $output_dir

aws s3 sync $output_dir s3://$bucket_name/files